projects:
  H2AuxInvest:
    schemaPath: amplify/backend/api/H2AuxInvest/build/schema.graphql
    includes:
      - src
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: eu-north-1
        apiId: null
        maxDepth: 10
