// tslint:disable
/**
 * h2AuxCalculatorApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-05-24T17:52:00Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DispensingRate,
    Mass,
    Pressure,
} from './';

/**
 * @export
 * @interface RequestSchema
 */
export interface RequestSchema {
    /**
     * @type {Pressure}
     * @memberof RequestSchema
     */
    hydrogen_inlet_pressure: Pressure;
    /**
     * @type {string}
     * @memberof RequestSchema
     */
    dispensing_type?: RequestSchemaDispensingTypeEnum;
    /**
     * @type {number}
     * @memberof RequestSchema
     */
    energy_price_per_mwh?: number;
    /**
     * @type {boolean}
     * @memberof RequestSchema
     */
    is_storage_required?: boolean;
    /**
     * @type {Mass}
     * @memberof RequestSchema
     */
    storage_mass?: Mass;
    /**
     * @type {Pressure}
     * @memberof RequestSchema
     */
    storage_pressure?: Pressure;
    /**
     * @type {Pressure}
     * @memberof RequestSchema
     */
    dispensing_pressure?: Pressure;
    /**
     * @type {DispensingRate}
     * @memberof RequestSchema
     */
    dispensing_mass?: DispensingRate;
    /**
     * @type {DispensingRate}
     * @memberof RequestSchema
     */
    avg_hydrogen_dispensing_rate?: DispensingRate;
    /**
     * @type {DispensingRate}
     * @memberof RequestSchema
     */
    peak_hydrogen_dispensing_rate?: DispensingRate;
    /**
     * @type {number}
     * @memberof RequestSchema
     */
    lifetime_years?: number;
    /**
     * @type {number}
     * @memberof RequestSchema
     */
    wacc?: number;
    /**
     * @type {boolean}
     * @memberof RequestSchema
     */
    is_precooling_used?: boolean;
    /**
     * @type {string}
     * @memberof RequestSchema
     */
    vehicle_type?: RequestSchemaVehicleTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum RequestSchemaDispensingTypeEnum {
    Tubetrailer = 'TUBETRAILER',
    Vehicle = 'VEHICLE'
}
/**
 * @export
 * @enum {string}
 */
export enum RequestSchemaVehicleTypeEnum {
    Tubetrailer = 'TUBETRAILER',
    Car = 'CAR',
    Hdv = 'HDV',
    Custom = 'CUSTOM'
}

