// tslint:disable
/**
 * h2AuxCalculatorApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-05-24T17:52:00Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ResponseSchemaDispensersInnerMeta
 */
export interface ResponseSchemaDispensersInnerMeta {
    /**
     * @type {string}
     * @memberof ResponseSchemaDispensersInnerMeta
     */
    title?: string;
    /**
     * @type {string}
     * @memberof ResponseSchemaDispensersInnerMeta
     */
    description?: string;
    /**
     * @type {Array<string>}
     * @memberof ResponseSchemaDispensersInnerMeta
     */
    positives?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof ResponseSchemaDispensersInnerMeta
     */
    negatives?: Array<string>;
}
