// tslint:disable
/**
 * h2AuxCalculatorApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-05-24T17:52:00Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ResponseSchemaDispensersInnerEquipment,
    ResponseSchemaDispensersInnerMeta,
} from './';

/**
 * @export
 * @interface ResponseSchemaCompressorsInner
 */
export interface ResponseSchemaCompressorsInner {
    /**
     * @type {string}
     * @memberof ResponseSchemaCompressorsInner
     */
    id?: string;
    /**
     * @type {ResponseSchemaDispensersInnerMeta}
     * @memberof ResponseSchemaCompressorsInner
     */
    meta?: ResponseSchemaDispensersInnerMeta;
    /**
     * @type {number}
     * @memberof ResponseSchemaCompressorsInner
     */
    power?: number;
    /**
     * @type {number}
     * @memberof ResponseSchemaCompressorsInner
     */
    cooling_energy?: number;
    /**
     * @type {number}
     * @memberof ResponseSchemaCompressorsInner
     */
    compression_energy?: number;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    equipment?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    equipment_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    installation?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    installation_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    maintenance?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    maintenance_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    energy?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    energy_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    sum_capex?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    sum_opex?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaCompressorsInner
     */
    sum_lcoh?: ResponseSchemaDispensersInnerEquipment;
}
