// tslint:disable
/**
 * h2AuxCalculatorApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-05-24T17:52:00Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ResponseSchemaDispensersInnerEquipment,
    ResponseSchemaDispensersInnerMeta,
    ResponseSchemaStorageInnerCapacity,
} from './';

/**
 * @export
 * @interface ResponseSchemaStorageInner
 */
export interface ResponseSchemaStorageInner {
    /**
     * @type {string}
     * @memberof ResponseSchemaStorageInner
     */
    id?: string;
    /**
     * @type {boolean}
     * @memberof ResponseSchemaStorageInner
     */
    _static?: boolean;
    /**
     * @type {ResponseSchemaDispensersInnerMeta}
     * @memberof ResponseSchemaStorageInner
     */
    meta?: ResponseSchemaDispensersInnerMeta;
    /**
     * @type {ResponseSchemaStorageInnerCapacity}
     * @memberof ResponseSchemaStorageInner
     */
    capacity?: ResponseSchemaStorageInnerCapacity;
    /**
     * @type {ResponseSchemaStorageInnerCapacity}
     * @memberof ResponseSchemaStorageInner
     */
    pressure?: ResponseSchemaStorageInnerCapacity;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    equipment?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    equipment_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    installation?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    installation_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    maintenance?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    maintenance_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    energy?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    energy_lcoh?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    sum_capex?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    sum_opex?: ResponseSchemaDispensersInnerEquipment;
    /**
     * @type {ResponseSchemaDispensersInnerEquipment}
     * @memberof ResponseSchemaStorageInner
     */
    sum_lcoh?: ResponseSchemaDispensersInnerEquipment;
}
