// tslint:disable
/**
 * h2AuxCalculatorApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-05-24T17:52:00Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ResponseSchemaCompressorsInner,
    ResponseSchemaDispensersInner,
    ResponseSchemaStorageInner,
} from './';

/**
 * @export
 * @interface ResponseSchema
 */
export interface ResponseSchema {
    /**
     * @type {string}
     * @memberof ResponseSchema
     */
    calculation_id?: string;
    /**
     * @type {Array<ResponseSchemaDispensersInner>}
     * @memberof ResponseSchema
     */
    dispensers?: Array<ResponseSchemaDispensersInner>;
    /**
     * @type {Array<ResponseSchemaCompressorsInner>}
     * @memberof ResponseSchema
     */
    compressors?: Array<ResponseSchemaCompressorsInner>;
    /**
     * @type {Array<ResponseSchemaStorageInner>}
     * @memberof ResponseSchema
     */
    storage?: Array<ResponseSchemaStorageInner>;
}
