# coding: utf-8

"""
    h2AuxCalculatorApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2018-05-24T17:52:00Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr, validator

class DispensingRate(BaseModel):
    """
    DispensingRate
    """
    value: Optional[Union[StrictFloat, StrictInt]] = None
    unit: Optional[StrictStr] = None
    __properties = ["value", "unit"]

    @validator('unit')
    def unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('KG_PER_HOUR', 'VEHICLES_PER_HOUR', 'VEHICLES_PER_DAY', 'KG_PER_YEAR'):
            raise ValueError("must be one of enum values ('KG_PER_HOUR', 'VEHICLES_PER_HOUR', 'VEHICLES_PER_DAY', 'KG_PER_YEAR')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DispensingRate:
        """Create an instance of DispensingRate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DispensingRate:
        """Create an instance of DispensingRate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DispensingRate.parse_obj(obj)

        _obj = DispensingRate.parse_obj({
            "value": obj.get("value"),
            "unit": obj.get("unit")
        })
        return _obj


