# coding: utf-8

"""
    h2AuxCalculatorApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2018-05-24T17:52:00Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from openapi_client.models.response_schema_compressors import ResponseSchemaCompressors
from openapi_client.models.response_schema_dispensers import ResponseSchemaDispensers
from openapi_client.models.response_schema_storage import ResponseSchemaStorage

class ResponseSchema(BaseModel):
    """
    ResponseSchema
    """
    calculation_id: Optional[StrictStr] = None
    dispensers: Optional[ResponseSchemaDispensers] = None
    compressors: Optional[ResponseSchemaCompressors] = None
    storage: Optional[ResponseSchemaStorage] = None
    __properties = ["calculation_id", "dispensers", "compressors", "storage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ResponseSchema:
        """Create an instance of ResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of dispensers
        if self.dispensers:
            _dict['dispensers'] = self.dispensers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of compressors
        if self.compressors:
            _dict['compressors'] = self.compressors.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage
        if self.storage:
            _dict['storage'] = self.storage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ResponseSchema:
        """Create an instance of ResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ResponseSchema.parse_obj(obj)

        _obj = ResponseSchema.parse_obj({
            "calculation_id": obj.get("calculation_id"),
            "dispensers": ResponseSchemaDispensers.from_dict(obj.get("dispensers")) if obj.get("dispensers") is not None else None,
            "compressors": ResponseSchemaCompressors.from_dict(obj.get("compressors")) if obj.get("compressors") is not None else None,
            "storage": ResponseSchemaStorage.from_dict(obj.get("storage")) if obj.get("storage") is not None else None
        })
        return _obj


